name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 只有当你 push tag（如 v1.0）时才触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # 或使用你项目使用的版本，如 6.0.x / 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Zip output
      run: |
        powershell Compress-Archive -Path ./publish/* -DestinationPath ./POE-Auto-Medicine.zip

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          自动构建发布版本：${{ github.ref_name }}
        files: POE-Auto-Medicine.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
